##
# Kubernetes deployment configuration for running a ClamAV daemon as an internal
# service, for use by Nextcloud's Antivirus app.
#
# With this configuration, Nextcloud can reach ClamAV on port 3310 at hostname
# "internal-clamav.NAMESPACE.svc.cluster.local" (aka "internal-clamav.NAMESPACE"
# or "internal-clamav" for short") within the cluster.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2019, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend-clamav
  template:
    metadata:
      labels:
        app: backend-clamav
        role: backend
    spec:
      containers:
        - name: backend-clamav
          image: "mkodockx/docker-clamav@sha256:09faf0d32b3f6f1169d2428e8226f2ea12bbb8fc3d96acc95ee1278f1a9f39c4"
#          imagePullPolicy: Always
          ports:
            - containerPort: 3310
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
      imagePullSecrets:
        # NOTE: This secret is added by `setup_aks_acr_service_principal.sh`.
        - name: "${ACR_DOCKER_CREDS_SECRET}"
---
apiVersion: v1
kind: Service
metadata:
  name: internal-clamav
  labels:
    role: internal-service
spec:
  ports:
    - name: clamav
      protocol: TCP
      port: 3310
  selector:
    app: backend-clamav
