##
# Kubernetes deployment configuration for running Nextcloud on PHP FPM with
# an Nginx reverse proxy.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2019, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: ${NEXTCLOUD_REPLICA_COUNT}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend-nextcloud
  template:
    metadata:
      labels:
        app: backend-nextcloud
        role: backend
    spec:
      containers:
        # Container: The PHP-FPM-based Nextcloud backend
        - name: backend-nextcloud-fpm
          image: "${REGISTRY_HOST}/inveniem/nextcloud-fpm:${CONTAINER_VERSION}"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1500m
              memory: 512Mi
          volumeMounts:
            - name: volume-nextcloud-app
              mountPath: /var/www/html
            # HACK: Until AKS supports pod presets, we have to kludge the dynamic
            # mounts in via a variable expansion. Do not modify the last line of
            # this comment; it gets expanded and replaced automatically when this
            # file is pre-processed. Remove this entire comment when switching over
            # to using pod presets.
            #
            # ${FILE_SHARE_VOLUME_MOUNT_LINES}
          env:
            - name: NEXTCLOUD_CONFIG_READ_ONLY
              value: "${NEXTCLOUD_CONFIG_READ_ONLY}"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: trusted_domains
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: "${KUBE_NEXTCLOUD_ADMIN_CREDS_SECRET}"
                  key: username
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${KUBE_NEXTCLOUD_ADMIN_CREDS_SECRET}"
                  key: password
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: "${KUBE_NEXTCLOUD_MYSQL_CREDS_SECRET}"
                  key: hostname
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "${KUBE_NEXTCLOUD_MYSQL_CREDS_SECRET}"
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: "${KUBE_NEXTCLOUD_MYSQL_CREDS_SECRET}"
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${KUBE_NEXTCLOUD_MYSQL_CREDS_SECRET}"
                  key: password
            - name: REDIS_HOST
              value: "internal-redis"
            - name: REDIS_PORT
              value: "6379"
        # Container: Nginx Server Middleware
        - name: middle-nextcloud-nginx
          image: "${REGISTRY_HOST}/inveniem/nextcloud-nginx-middleware:${CONTAINER_VERSION}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: volume-nextcloud-app
              mountPath: /var/www/html
              readOnly: true
          readinessProbe:
            httpGet:
              # This path should work both before and after installation.
              # In local testing, Nextcloud serves up the installer regardless
              # of which URL is provided.
              path: "/index.php/login?direct=1"
              port: 80
              httpHeaders:
                - name: "Host"
                  value: "${NEXTCLOUD_PRIMARY_HOSTNAME}"
            # Wait 30 seconds after launch before checking for readiness
            # (to allow for automated updates at launch)
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            # Ensure stability across two checks before continuing to route
            # traffic, so we don't sawtooth during heavy request load between
            # being available-unavailable-available-unavailable.
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: "/status.php"
              port: 80
              httpHeaders:
                - name: "Host"
                  value: "${NEXTCLOUD_PRIMARY_HOSTNAME}"
            # Wait 5 minutes after launch before checking for liveness
            # (to allow for automated updates at launch)
            initialDelaySeconds: 300
            periodSeconds: 5
            timeoutSeconds: 10
            # Restart container after it is down for 60 seconds
            failureThreshold: 12
            successThreshold: 1
      imagePullSecrets:
        # NOTE: This secret is added by `setup_aks_acr_service_principal.sh`.
        - name: "${ACR_DOCKER_CREDS_SECRET}"
      volumes:
        # Ephemeral volume that contains the loaded Nextcloud software,
        # shared between the Nextcloud PHP-FPM and Nginx containers within the
        # same pod
        - name: volume-nextcloud-app
          emptyDir: {}
        # HACK: Until AKS supports pod presets, we have to kludge the dynamic
        # mounts in via a variable expansion. Do not modify the last line of
        # this comment; it gets expanded and replaced automatically when this
        # file is pre-processed. Remove this entire comment when switching over
        # to using pod presets.
        #
        # ${FILE_SHARE_VOLUME_LINES}
---
apiVersion: v1
kind: Service
metadata:
  name: internal-nextcloud
  labels:
    role: internal-service
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: backend-nextcloud
